# /// script
# requires-python = ">=3.11"
# dependencies = ["duckdb", "rapidfuzz", "httpx"]
# ///
"""
Local-LLM plain-language condition translator (arm B).

Asks an Ollama-hosted small instruction-tuned model to produce keyword
lists for a condition in a fixed JSON schema, then feeds those keywords
through the **same deterministic scoring pipeline as arm A** (pfs_codes.csv
keyword overlap, taxonomy.csv specialty matching, cms.duckdb specialty
filter, PubMed query assembly). The LLM emits free-form keywords; HCPCS
codes, taxonomy codes, and CMS specialty names are grounded against real
reference data — not generated by the model — so hallucinated codes never
reach the output.

Model is selected via env var (OLLAMA_MODEL) or CLI flag. The harness
passes the model through OLLAMA_MODEL before importing this module.

    OLLAMA_MODEL=qwen2.5:3b-instruct-q4_K_M uv run eval/harness.py --arm llm

No caching. Retries JSON parsing once, then raises.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

import httpx

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from condition_profile import ConditionProfile  # noqa: E402
from translator_deterministic import (  # noqa: E402
    _build_pubmed_queries,
    _match_cms_specialties,
    _score_hcpcs,
    _score_taxonomy,
)

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434")
DEFAULT_MODEL = "qwen2.5:3b-instruct-q4_K_M"
PROBE_TIMEOUT = 2.0
GENERATE_TIMEOUT = 120.0


SYSTEM_PROMPT = """You are a medical-coding assistant. For a given plain-language medical condition, you produce a JSON object with keyword lists used downstream to match HCPCS procedure descriptions, NUCC taxonomy definitions, and CMS specialty names.

Output ONLY a single valid JSON object. No markdown fences, no preamble, no explanation.

Schema (all values are arrays of short lowercase strings):
  aliases              : clinical and lay names for the condition (e.g. "tennis elbow", "lateral epicondylitis")
  anatomy_keywords     : anatomical structures, body parts, labs, biomarkers relevant to the condition (e.g. "elbow", "tendon", "hemoglobin a1c")
  procedure_keywords   : treatment/diagnostic procedure vocabulary as it appears in HCPCS descriptions (e.g. "injection", "biopsy", "endoscope", "arthroscopy")
  mesh_terms           : MeSH-style search terms for PubMed literature search
  specialty_hints      : physician specialty substrings, lowercase, as they appear in "Internal Medicine", "Orthopedic Surgery", etc.

Two worked examples:

Condition: piriformis syndrome
{"aliases":["piriformis syndrome","deep gluteal syndrome","extraspinal sciatica","piriformis muscle syndrome"],"anatomy_keywords":["piriformis","sciatic","gluteal","hip","sacroiliac","peripheral nerve","muscle"],"procedure_keywords":["trigger point","nerve conduction","nerve block","ultrasonic guidance","fluoroscopic guidance","facet joint","botulinum","steroid"],"mesh_terms":["piriformis muscle syndrome","sciatica","nerve compression syndromes"],"specialty_hints":["physical medicine","neurology","orthopedic","sports medicine","interventional radiology","pain management","anesthesiology"]}

Condition: tennis elbow
{"aliases":["tennis elbow","lateral epicondylitis","lateral elbow tendinopathy","extensor carpi radialis brevis tendinopathy"],"anatomy_keywords":["elbow","tendon","lateral","epicondyle","extensor","forearm"],"procedure_keywords":["injection","incision","tenotomy","shock wave","debridement","arthroscopy","endoscope","platelet rich plasma","imaging guidance"],"mesh_terms":["tennis elbow","lateral epicondylitis","tendinopathy"],"specialty_hints":["orthopedic","sports medicine","physical medicine","hand surgery"]}
"""

USER_TEMPLATE = "Condition: {term}\n"

# Passed to Ollama's `format` field (not just "json"). Ollama does
# grammar-constrained decoding against this schema, so any model that
# speaks JSON is forced to emit exactly our keys. This matters
# especially for less strongly instruction-tuned models like
# meditron:7b which otherwise fall back to learned JSON patterns.
JSON_SCHEMA = {
    "type": "object",
    "properties": {
        "aliases": {"type": "array", "items": {"type": "string"}},
        "anatomy_keywords": {"type": "array", "items": {"type": "string"}},
        "procedure_keywords": {"type": "array", "items": {"type": "string"}},
        "mesh_terms": {"type": "array", "items": {"type": "string"}},
        "specialty_hints": {"type": "array", "items": {"type": "string"}},
    },
    "required": [
        "aliases", "anatomy_keywords", "procedure_keywords",
        "mesh_terms", "specialty_hints",
    ],
}


def _probe() -> None:
    try:
        r = httpx.get(f"{OLLAMA_URL}/api/tags", timeout=PROBE_TIMEOUT)
        r.raise_for_status()
    except Exception as e:
        raise RuntimeError(
            f"ollama not reachable at {OLLAMA_URL}: {e}\n"
            f"Start ollama with: ollama serve"
        ) from e


def _generate(model: str, term: str) -> str:
    body = {
        "model": model,
        "prompt": SYSTEM_PROMPT + "\n" + USER_TEMPLATE.format(term=term),
        "stream": False,
        "format": JSON_SCHEMA,
        "options": {"temperature": 0.0},
    }
    r = httpx.post(
        f"{OLLAMA_URL}/api/generate",
        json=body,
        timeout=GENERATE_TIMEOUT,
    )
    r.raise_for_status()
    return r.json()["response"]


def _parse_json(text: str) -> dict:
    text = text.strip()
    # Strip markdown fences if the model added them despite instructions.
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```\s*$", "", text)
    # Greedy-match the first balanced JSON object.
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        text = m.group(0)
    return json.loads(text)


def _validate_entry(data: dict) -> dict:
    required = [
        "aliases",
        "anatomy_keywords",
        "procedure_keywords",
        "mesh_terms",
        "specialty_hints",
    ]
    missing = [k for k in required if k not in data]
    if missing:
        got = list(data.keys())
        raise ValueError(
            f"llm output missing required keys: {missing}. "
            f"got keys: {got}. sample: {str(data)[:400]!r}"
        )
    for key in required:
        if not isinstance(data[key], list):
            raise ValueError(
                f"llm output key {key!r} is not a list: "
                f"got {type(data[key]).__name__}={data[key]!r}"
            )
        data[key] = [str(x).strip().lower() for x in data[key] if x]
    return data


def _slugify(term: str) -> str:
    return "-".join(term.lower().strip().split())


def translate(term: str) -> ConditionProfile:
    model = os.environ.get("OLLAMA_MODEL", DEFAULT_MODEL)
    _probe()
    raw = _generate(model, term)
    try:
        data = _parse_json(raw)
    except json.JSONDecodeError:
        raw2 = _generate(model, term)
        try:
            data = _parse_json(raw2)
        except json.JSONDecodeError as e:
            raise RuntimeError(
                f"llm {model} returned non-JSON twice for {term!r}: "
                f"{raw[:300]!r}"
            ) from e
    entry = _validate_entry(data)
    return ConditionProfile(
        slug=_slugify(term),
        pubmed_queries=_build_pubmed_queries(entry),
        hcpcs_weights=_score_hcpcs(entry),
        cms_specialties=_match_cms_specialties(entry),
        taxonomy_codes=_score_taxonomy(entry),
    )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("term", help="plain-language condition term")
    parser.add_argument(
        "--model",
        default=None,
        help="ollama model tag (overrides $OLLAMA_MODEL)",
    )
    args = parser.parse_args()
    if args.model:
        os.environ["OLLAMA_MODEL"] = args.model
    profile = translate(args.term)
    print(profile.to_json())
